import csv
import numpy as np
import random
from operator import add, sub

# Instruction file generated by varying the number of processors
num_processors = 16


addresses = random.sample(range(0, 2**32-1), 1000)
close_range = random.sample(range(0, 1000), 100)
# print(addresses)

insts = []
ops = (add, sub)


for i in range(len(addresses)):
    insts.append(hex(addresses[i]))

    for j in range(len(close_range)):
        op = random.choice(ops)        
        insts.append(hex(op(addresses[i], random.choice(close_range))))

random.shuffle(insts)

for_exclusive = random.sample(range(0, 2**32-1), 100)
for_exclusive_insts = []
for i in for_exclusive:
    for_exclusive_insts.append(hex(i))

instructions = []
time = 0
# instruction = [time, processor, address, access_type, num of bytes to access]
for i in range(len(insts)):
    instructions.append([time, random.randint(0, num_processors-1), insts[i], random.randint(0, 1), random.randint(0, 4)])
    time+=1

for i in range(len(for_exclusive_insts)):
    # Read on exclusive
    instructions.append([time, random.randint(0, num_processors-1), for_exclusive_insts[i], 0, random.randint(0, 4)])
    time+=1

for i in range(len(for_exclusive_insts)):
    # Write on exclusive
    instructions.append([time, random.randint(0, num_processors-1), for_exclusive_insts[i], 1, random.randint(0, 4)])
    time+=1

print(len(instructions))
print(instructions[0])
    
file_name = 'insts_'+str(num_processors)+'_cores.csv'
print(file_name)
with open(file_name, mode="w", newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(instructions)